---

services:
  mdfanchanger:
    container_name: snmpython-dev
    user: 1600:1600
    image: shupotea/yuruc3/snmpython:dev
    build:
      dockerfile: ./Dockerfile
    environment:
      - INFLUXTOKEN=12345678
      - INFLUXHOST=123

      - HOST_LIST="["192.168.0.1", "192.168.0.1", "192.168.0.1", "192.168.0.1"]"
    # restart: unless-stopped
    restart: never
    
