---

services:
  snmpcollector:
    container_name: snmpython-dev
    user: 1600:1600
    image: shupotea/yuruc3/snmpython:dev
    build:
      dockerfile: ./Dockerfile
    environment:
      - USEINFLUX=1
      - INFLXDBTOKEN=67676767
      - INFLUXBCKT=pyusr-DEV
      - INFLUXORG=staging
      - INFLXDBURL=http://influxdb:8086
      - INFXLUXDB_MEASUEREMENT=dev-pycollector

      - USESQL=1
      - DBADDR=mariadb
      - DBUSR=root
      - DBPWD=67676767
      - DBNAME=pyCollector

      - SNMPUSER=SNMPusrRO
      - SNMPPRIVKEY=67676767
      - SNMPAUTHKEY=67676767

      - IDRAC_HOST_LIST=192.168.0.1;192.168.0.1;192.168.0.1;192.168.0.1
      - CISCO_HOST_LIST=192.168.0.1;192.168.0.1;192.168.0.1;192.168.0.1
      # - HOST_LIST=192.168.20.7
    # restart: unless-stopped
    restart: no

  influxdb:
    image: influxdb:2.7
    container_name: influxdb-test
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=yuru
      - DOCKER_INFLUXDB_INIT_PASSWORD=67676767
      - DOCKER_INFLUXDB_INIT_ORG=staging
      - DOCKER_INFLUXDB_INIT_BUCKET=pyusr-DEV
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=67676767
    volumes:
      - influx:/var/lib/influxdb2
    restart: unless-stopped

  mariadb:
    container_name: uberAPI-mdb
    image: mariadb:latest
    restart: always
    volumes:
      - mdb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "67676767"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8180:8080"
  
volumes:
  influx:
  mdb:    
